# ---------------------------------------------------------------------------
# This Isar layer is part of MTDA
# Copyright (C) 2026 Siemens AG
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

require conf/distro/debian-trixie.conf
