# ---------------------------------------------------------------------------
# Base kas file for all configurations
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2025 Siemens AG
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

header:
  version: 17

machine: qemuamd64
target: mtda-image

repos:
  mtda:
    layers:
      meta-isar:
  isar:
    url: https://github.com/ilbers/isar.git
    commit: d46adc844a74ba55c4b9521b7d7da9b5a47b489e
    layers:
      meta:
      meta-isar:
    patches:
      01-wicvars-efi:
        repo: mtda
        path: patches/isar/0001-wic-add-IMAGE_EFI_BOOT_FILES-to-WICVARS.patch

bblayers_conf_header:
  base: |
    LCONF_VERSION = "6"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    CONF_VERSION = "1"
    ISAR_CROSS_COMPILE = "1"
  ccache: |
    USE_CCACHE = "1"
