# ---------------------------------------------------------------------------
# Base kas file for all configurations
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2025 Siemens AG
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

header:
  version: 17

machine: qemuamd64
target: mtda-image

repos:
  mtda:
    layers:
      meta-isar:
  isar:
    url: https://github.com/ilbers/isar.git
    commit: b5f7aef4e4fd26d852f8b09e545d5ade551224df
    layers:
      meta:
      meta-isar:

bblayers_conf_header:
  base: |
    LCONF_VERSION = "6"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  base: |
    CONF_VERSION = "1"
    ISAR_CROSS_COMPILE = "1"
  ccache: |
    USE_CCACHE = "1"
