#!/bin/sh

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)
    ischroot || /usr/sbin/mtda-systemd-helper || exit ${?}
    if ! grep -qe '^libcomposite$' /etc/modules; then
      echo "libcomposite" >/etc/modules || exit ${?}
    fi
    if ! getent passwd mtda >/dev/null; then
      adduser --system --group --home /var/lib/mtda --disabled-login mtda
    fi
    ;;

esac

#DEBHELPER#
