#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# Check if versions in debian/changelog and mtda/__version__.py agree
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (c) Mentor, a Siemens business, 2017-2021
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

import subprocess
import sys

from mtda import __version__

# Extract version from debian/changelog
cmd = [ "dpkg-parsechangelog", "-S", "Version" ]
deb_version = subprocess.check_output(cmd, encoding="utf-8").strip()
deb_version = deb_version.split("-")[0]

# Compare against version specified in the "mtda" module
if deb_version != __version__:
    print("version in debian/changelog is '{0}' but was expecting '{1}'".format(deb_version, __version__))
    sys.exit(1)
sys.exit(0)
